version: '4'
services:
  app:
    build:
      context: 'docker/development'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    depends_on:
      - app_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  app_db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: receipt
      MYSQL_DATABASE: receipt
      MYSQL_USER: receipt
      MYSQL_PASSWORD: receipt
    ports:
      - "3306:3306"
    volumes:
      - app_db_data:/var/lib/mysql

volumes:
  app_db_data:
