version: '4'
services:
  app:
    build:
      context: 'docker/development'
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      NODE_ENV: development
      DEBUG: "receipt-tracker:*"
      DATABASE_URL: "mysql://root:receipt@app_db:3306/receipt"
    depends_on:
      - app_db
  app_db:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: receipt
      MYSQL_DATABASE: receipt
      MYSQL_USER: receipt
      MYSQL_PASSWORD: receipt
    ports:
      - "3306:3306"
    volumes:
      - app_db_data:/var/lib/mysql

volumes:
  app_db_data:
